# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "rack"
gem "unicorn"
gem 'bigdecimal'
gem "mysql2-cs-bind"
gem "rack-flash3"
gem 'connection_pool'
gem "dalli"
